// src/components/CharacterSheet.vue
<template>
  <div class="col container">
    <div class="row-mobile-col">
      <!-- <div class="frame">
        <button id="portrait-upload">
          <img
            id="char-portrait"
            src="https://i.pinimg.com/originals/c6/fc/2c/c6fc2c165498a2f39b420b1e75aa2017.png"
            alt="Character Portrait"
          />
        </button>
      </div> -->
      <div class="col title-row">
        <div id="char-name">
          <input v-model="name" type="text" placeholder="Character Name" />
        </div>
        <div id="char-title" class="row-mobile-col">
          <div class="title-prefix">the</div>
          <input v-model="title" type="text" placeholder="Character Title" />
        </div>
      </div>
    </div>
    <div class="spacer-sheet" />
    <div class="row-mobile-col m-spaced">
      <div class="col-mobile-row m-spaced char-attribute">
        <div class="attribute-label">Brawn</div>
        <number-input
          class="char-attr-grid"
          v-model="brawn"
          :min="-1"
          :max="3"
        />
      </div>
      <div class="col-mobile-row m-spaced char-attribute">
        <div class="attribute-label">Poise</div>
        <number-input
          class="char-attr-grid"
          v-model="poise"
          :min="-1"
          :max="3"
        />
      </div>
      <div class="col-mobile-row m-spaced char-attribute">
        <div class="attribute-label">Memory</div>
        <number-input
          class="char-attr-grid"
          v-model="memory"
          :min="-1"
          :max="3"
        />
      </div>
      <div class="col-mobile-row m-spaced char-attribute">
        <div class="attribute-label">Wit</div>
        <number-input class="char-attr-grid" v-model="wit" :min="-1" :max="3" />
      </div>
      <div class="col-mobile-row m-spaced char-attribute">
        <div class="attribute-label">Charisma</div>
        <number-input
          class="char-attr-grid"
          v-model="charisma"
          :min="-1"
          :max="3"
        />
      </div>
    </div>
    <div class="spacer-sheet" />
    <div class="trackers">
      <div v-if="!dead" class="col">
        <div class="dmg-grid">
          <div>Damage</div>
          <div class="row m-center c-center">
            <number-input class="row minor-stat" v-model="damage" :min="0" />
          </div>
          <div />
          <div class="dmg-over-thresh" />
          <div>Threshold</div>
          <div class="txt-center">{{ threshold }}</div>
          <div class="thresh-over-wounds">
            <button class="basic-input" @click="resolveDamage">Resolve</button>
          </div>
          <div>Wounds</div>
          <div class="txt-center">{{ wounds }}</div>
        </div>
        <div class="row">
          <div class="rest-label">Rest</div>
          <button class="basic-input left grow" @click="rest(1)">
            Partial
          </button>
          <button class="basic-input right grow" @click="rest(3)">
            Full Day
          </button>
        </div>
      </div>
      <div v-else class="col">
        <div class="txt-center">Dead</div>
        <button class="basic-input" @click="revive">Resurrect</button>
      </div>
      <div class="col defense other-trackers">
        <div class="row m-spaced">
          <div>Armor</div>
          <number-input
            class="row m-center minor-stat basic-input"
            v-model="armor"
            :min="-99"
            :max="99"
            textOnly
          />
        </div>
        <div class="row m-spaced">
          <div>Speed</div>
          <number-input
            class="row m-center minor-stat basic-input"
            v-model="speed"
            :min="-99"
            :max="99"
            textOnly
          />
        </div>
      </div>
      <div class="col other-trackers">
        <div class="row m-spaced">
          <div>Cognition</div>
          <div class="row">
            <number-input
              class="row m-center minor-stat"
              v-model="cognition"
              :min="0"
              :max="cognitionMax"
            />
            <div class="out-of">of {{ cognitionMax }}</div>
          </div>
        </div>
        <div class="row">
          <button class="basic-input left grow" @click="sleep(0.5)">Nap</button>
          <button class="basic-input right grow" @click="sleep(1)">
            Sleep
          </button>
        </div>
        <div class="row">
          <bs
            id="meal-type"
            class="food-type-select"
            @select="handleFoodSelect"
            :options="foodTypes"
            :initial="1"
          />
          <button id="eat-button" class="grow basic-input right" @click="eat">
            Eat
          </button>
        </div>
      </div>
    </div>
    <div class="spacer-sheet" />
    <div class="col">
      <div class="row m-spaced c-center">
        <h1 class="row c-center">Injuries</h1>
        <div class="row injury-controls">
          <bs
            class="injury-type-select"
            :options="injuryTypes"
            @select="handleInjurySelect"
          />
          <button class="injury-add-bttn basic-input right" @click="addInjury">
            +
          </button>
        </div>
      </div>
      <div class="col injury-list">
        <div class="col injury-list-entry" v-if="totalDot > 0">
          <div class="row stat-injury-grid">
            <div>Damage Over Time</div>
            <div>{{ dotRange }}</div>
          </div>
          <button @click="applyDot">Apply</button>
          <div class="row">
            <button
              class="grow"
              @click="heal('minorDot')"
              :disabled="minorDot < 1"
            >
              Heal Minor [{{ minorDot }}]
            </button>
            <button
              class="grow"
              @click="heal('severeDot')"
              :disabled="severeDot < 1"
            >
              Heal Major [{{ severeDot }}]
            </button>
          </div>
        </div>
        <div class="col injury-list-entry" v-if="totalSlow > 0">
          <div class="row stat-injury-grid">
            <div>Slowed</div>
            <div>
              {{ immobile > 0 ? 'Speed to 0' : `Speed -${slowed}` }}
            </div>
          </div>
          <div class="row">
            <button class="grow" @click="heal('slowed')" :disabled="slowed < 1">
              Heal Minor [{{ slowed }}]
            </button>
            <button
              class="grow"
              @click="heal('immobile')"
              :disabled="immobile < 1"
            >
              Heal Major [{{ immobile }}]
            </button>
          </div>
        </div>
        <div class="col injury-list-entry" v-if="totalWeaken > 0">
          <div class="row stat-injury-grid">
            <div>Weakened</div>
            <div>
              {{ drained > 0 ? 'Brawn to 0' : `Brawn -${weakened}` }}
            </div>
          </div>
          <div class="row">
            <button
              class="grow"
              @click="heal('weakened')"
              :disabled="weakened < 1"
            >
              Heal Minor [{{ weakened }}]
            </button>
            <button
              class="grow"
              @click="heal('drained')"
              :disabled="drained < 1"
            >
              Heal Major [{{ drained }}]
            </button>
          </div>
        </div>
        <div class="col injury-list-entry" v-if="totalStagger > 0">
          <div class="row stat-injury-grid">
            <div>Staggered</div>
            <div>
              {{ unstable > 0 ? 'Poise to 0' : `Poise -${staggered}` }}
            </div>
          </div>
          <div class="row">
            <button
              class="grow"
              @click="heal('staggered')"
              :disabled="staggered < 1"
            >
              Heal Minor [{{ staggered }}]
            </button>
            <button
              class="grow"
              @click="heal('unstable')"
              :disabled="unstable < 1"
            >
              Heal Major [{{ unstable }}]
            </button>
          </div>
        </div>
        <div class="col injury-list-entry" v-if="totalDistraction > 0">
          <div class="row stat-injury-grid">
            <div>Distracted</div>
            <div>
              {{ amnesia > 0 ? 'Memory to 0' : `Memory -${distracted}` }}
            </div>
          </div>
          <div class="row">
            <button
              class="grow"
              @click="heal('distracted')"
              :disabled="distracted < 1"
            >
              Heal Minor [{{ distracted }}]
            </button>
            <button
              class="grow"
              @click="heal('amnesia')"
              :disabled="amnesia < 1"
            >
              Heal Major [{{ amnesia }}]
            </button>
          </div>
        </div>
        <div class="col injury-list-entry" v-if="totalDull > 0">
          <div class="row stat-injury-grid">
            <div>Dulled</div>
            <div>
              {{ dazed > 0 ? 'Wit to 0' : `Wit -${dulled}` }}
            </div>
          </div>
          <div class="row">
            <button class="grow" @click="heal('dulled')" :disabled="dulled < 1">
              Heal Minor [{{ dulled }}]
            </button>
            <button class="grow" @click="heal('dazed')" :disabled="dazed < 1">
              Heal Major [{{ dazed }}]
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="spacer-sheet" />
    <div class="col reference-list">
      <h1 class="reference-list-section-title" @click="close">
        <g-link to="/characters/proficiencies">Proficiencies</g-link>
      </h1>
      <div class="empty-reference-list" v-if="proficiencies.length < 1">
        None... Go to the Proficiencies page of the rules to add some.
      </div>
      <reference-entry
        v-for="entry in proficiencies"
        :key="entry"
        :entry="entry"
        @close="close"
        @remove="removeProficiency"
        baseRulesUrl="/characters/proficiencies"
        baseRefUrl="/ref/proficiencies"
      />
    </div>
    <div class="spacer-sheet" />
    <div class="col reference-list">
      <h1 class="reference-list-section-title" @click="close">
        <g-link to="/characters/traits">Traits</g-link>
      </h1>
      <h2 class="reference-list-section-title" @click="close">
        <g-link to="/characters/traits/mundane">Mundane</g-link>
      </h2>
      <div class="empty-reference-list" v-if="mundaneTraits.length < 1">
        None... Go to the Mundane Traits page of the rules to add some.
      </div>
      <div class="col">
        <reference-entry
          v-for="entry in mundaneTraits"
          :key="entry"
          :entry="entry"
          @close="close"
          @remove="removeMundaneTrait"
          baseRulesUrl="/characters/traits/mundane"
          baseRefUrl="/ref/traits/mundane"
        />
      </div>
      <h2 class="reference-list-section-title" @click="close">
        <g-link to="/characters/traits/exceptional">Exceptional</g-link>
      </h2>
      <div class="empty-reference-list" v-if="heroicTraits.length < 1">
        None... Go to the Heroic Traits page of the rules to add some.
      </div>
      <div class="col">
        <reference-entry
          v-for="entry in heroicTraits"
          :key="entry"
          :entry="entry"
          @close="close"
          @remove="removeHeroicTrait"
          baseRulesUrl="/characters/traits/exceptional"
          baseRefUrl="/ref/traits/exceptional"
        />
      </div>
    </div>
  </div>
</template>

<script>
import NumberInput from '~/components/NumberInput.vue'
import ReferenceEntry from '~/components/ReferenceEntry.vue'

export default {
  components: {
    NumberInput: NumberInput,
    ReferenceEntry: ReferenceEntry,
  },
  data() {
    return {
      foodTypes: [
        {
          label: 'Questionable',
          value: [-4, 1],
        },
        {
          label: 'Snack',
          value: [2],
        },
        {
          label: 'Decent Meal',
          value: [4],
        },
        {
          label: 'Good Meal',
          value: [8],
        },
        {
          label: 'Hearty Meal',
          value: [12],
        },
      ],
      foodValue: [2],
      injuryTypes: [
        {
          label: 'Minor Injuries',
          options: [
            {
              label: 'Minor DoT',
              value: 'minorDot',
            },
            {
              label: 'Slowed',
              value: 'slowed',
            },
            {
              label: 'Weakened',
              value: 'weakened',
            },
            {
              label: 'Staggered',
              value: 'staggered',
            },
            {
              label: 'Distracted',
              value: 'distracted',
            },
            {
              label: 'Dulled Senses',
              value: 'dulled',
            },
          ],
        },
        {
          label: 'Severe Injuries',
          options: [
            {
              label: 'Severe DoT',
              value: 'severeDot',
            },
            {
              label: 'Immobile',
              value: 'immobile',
            },
            {
              label: 'Drained',
              value: 'drained',
            },
            {
              label: 'Unstable',
              value: 'unstable',
            },
            {
              label: 'Amnesia',
              value: 'amnesia',
            },
            {
              label: 'Dazed',
              value: 'Dazed',
            },
          ],
        },
      ],
    }
  },
  computed: {
    name: {
      get() {
        return this.$store.state.character.name
      },
      set(value) {
        this.$store.commit('setCharacterName', value)
        this.$store.dispatch('save')
      },
    },
    title: {
      get() {
        return this.$store.state.character.title
      },
      set(value) {
        this.$store.commit('setCharacterTitle', value)
        this.$store.dispatch('save')
      },
    },
    brawn: {
      get() {
        return this.$store.state.character.brawn
      },
      set(value) {
        this.$store.commit('setCharacterBrawn', value)
        this.$store.dispatch('save')
      },
    },
    poise: {
      get() {
        return this.$store.state.character.poise
      },
      set(value) {
        this.$store.commit('setCharacterPoise', value)
        this.$store.dispatch('save')
      },
    },
    memory: {
      get() {
        return this.$store.state.character.memory
      },
      set(value) {
        this.$store.commit('setCharacterMemory', value)
        this.$store.dispatch('save')
      },
    },
    wit: {
      get() {
        return this.$store.state.character.wit
      },
      set(value) {
        this.$store.commit('setCharacterWit', value)
        this.$store.dispatch('save')
      },
    },
    charisma: {
      get() {
        return this.$store.state.character.charisma
      },
      set(value) {
        this.$store.commit('setCharacterCharisma', value)
        this.$store.dispatch('save')
      },
    },
    damage: {
      get() {
        return this.$store.state.character.damage
      },
      set(value) {
        this.$store.commit('setCharacterDamage', value)
        this.$store.dispatch('save')
      },
    },
    threshold: {
      get() {
        return (
          4 +
          this.$store.state.character.brawn * 2 +
          this.$store.state.character.poise
        )
      },
    },
    wounds: {
      get() {
        return this.$store.state.character.wounds
      },
      set(value) {
        this.$store.commit('setCharacterWounds', value)
        this.$store.dispatch('save')
      },
    },
    armor: {
      get() {
        return this.$store.state.character.armor
      },
      set(value) {
        this.$store.commit('setCharacterArmor', value)
        this.$store.dispatch('save')
      },
    },
    speed: {
      get() {
        return this.$store.state.character.speed
      },
      set(value) {
        this.$store.commit('setCharacterSpeed', value)
        this.$store.dispatch('save')
      },
    },
    cognition: {
      get() {
        return this.$store.state.character.cognition
      },
      set(value) {
        this.$store.commit('setCharacterCognition', value)
        this.$store.dispatch('save')
      },
    },
    cognitionMax: {
      get() {
        const wit = this.$store.state.character.wit
        return wit > -1 ? 8 + wit * 8 : 8 / Math.pow(2, Math.abs(wit))
      },
    },
    minorDot: {
      get() {
        return this.$store.state.character.injuries.minorDot
      },
      set(value) {
        this.$store.commit('setCharacterMinorDot', value)
        this.$store.dispatch('save')
      },
    },
    severeDot: {
      get() {
        return this.$store.state.character.injuries.severeDot
      },
      set(value) {
        this.$store.commit('setCharacterSevereDot', value)
        this.$store.dispatch('save')
      },
    },
    slowed: {
      get() {
        return this.$store.state.character.injuries.slowed
      },
      set(value) {
        this.$store.commit('setCharacterSlowed', value)
        this.$store.dispatch('save')
      },
    },
    immobile: {
      get() {
        return this.$store.state.character.injuries.immobile
      },
      set(value) {
        this.$store.commit('setCharacterImmobile', value)
        this.$store.dispatch('save')
      },
    },
    weakened: {
      get() {
        return this.$store.state.character.injuries.weakened
      },
      set(value) {
        this.$store.commit('setCharacterWeakened', value)
        this.$store.dispatch('save')
      },
    },
    drained: {
      get() {
        return this.$store.state.character.injuries.drained
      },
      set(value) {
        this.$store.commit('setCharacterDrained', value)
        this.$store.dispatch('save')
      },
    },
    staggered: {
      get() {
        return this.$store.state.character.injuries.staggered
      },
      set(value) {
        this.$store.commit('setCharacterStaggered', value)
        this.$store.dispatch('save')
      },
    },
    unstable: {
      get() {
        return this.$store.state.character.injuries.unstable
      },
      set(value) {
        this.$store.commit('setCharacterUnstable', value)
        this.$store.dispatch('save')
      },
    },
    distracted: {
      get() {
        return this.$store.state.character.injuries.distracted
      },
      set(value) {
        this.$store.commit('setCharacterDistracted', value)
        this.$store.dispatch('save')
      },
    },
    amnesia: {
      get() {
        return this.$store.state.character.injuries.amnesia
      },
      set(value) {
        this.$store.commit('setCharacterAmnesia', value)
        this.$store.dispatch('save')
      },
    },
    dulled: {
      get() {
        return this.$store.state.character.injuries.dulled
      },
      set(value) {
        this.$store.commit('setCharacterDulled', value)
        this.$store.dispatch('save')
      },
    },
    dazed: {
      get() {
        return this.$store.state.character.injuries.dazed
      },
      set(value) {
        this.$store.commit('setCharacterDazed', value)
        this.$store.dispatch('save')
      },
    },
    proficiencies: {
      get() {
        return this.$store.state.character.proficiencies
      },
    },
    mundaneTraits: {
      get() {
        return this.$store.state.character.mundaneTraits
      },
    },
    heroicTraits: {
      get() {
        return this.$store.state.character.heroicTraits
      },
    },
    dead() {
      return this.wounds >= this.threshold
    },
    totalDot() {
      return this.minorDot + this.severeDot
    },
    dotRange() {
      const minorDotTotal = this.minorDot > 0 ? `${this.minorDot}` : ''
      const combined = this.minorDot > 0 && this.severeDot > 0 ? ' + ' : ''
      const severeDotTotal = this.severeDot > 0 ? `${this.severeDot}d3` : ''
      return minorDotTotal + combined + severeDotTotal
    },
    totalSlow() {
      return this.slowed + this.immobile
    },
    totalWeaken() {
      return this.weakened + this.drained
    },
    totalStagger() {
      return this.staggered + this.unstable
    },
    totalDistraction() {
      return this.distracted + this.amnesia
    },
    totalDull() {
      return this.dulled + this.dazed
    },
  },
  watch: {
    damage(val, old) {
      if (this.damage < this.wounds) this.damage = this.wounds
    },
    wounds(val, old) {
      if (this.damage < this.wounds) this.damage = this.wounds
    },
  },
  methods: {
    close() {
      this.$emit('close')
    },
    removeProficiency(target) {
      this.$store.commit('removeProficiency', target)
      this.$store.dispatch('save')
    },
    removeMundaneTrait(target) {
      this.$store.commit('removeMundaneTrait', target)
      this.$store.dispatch('save')
    },
    removeHeroicTrait(target) {
      this.$store.commit('removeHeroicTrait', target)
      this.$store.dispatch('save')
    },
    resolveDamage() {
      if (this.damage < this.threshold) return
      const newWounds = Math.floor(this.damage / this.threshold)
      if (newWounds > 2) this.wounds = this.threshold
      else this.wounds += newWounds
      this.damage = this.wounds
    },
    rest(amount) {
      if (this.dead) return
      this.wounds = Math.max(0, this.wounds - amount)
      this.damage = this.wounds
    },
    revive() {
      this.wounds = Math.max(0, this.threshold - 1)
      this.damage = this.wounds
    },
    sleep(scale) {
      this.cognition = Math.min(
        this.cognition + Math.ceil(scale * this.cognitionMax),
        this.cognitionMax,
      )
    },
    handleInjurySelect(option) {
      this.selectedInjury = option.value
    },
    addInjury() {
      if (
        !this.$store.state.character.injuries.hasOwnProperty(
          this.selectedInjury,
        )
      )
        return
      const current = this[this.selectedInjury]
      this[this.selectedInjury] = current + 1
    },
    handleFoodSelect(option) {
      this.foodValue = option.value
    },
    eat() {
      this.cognition += this.foodValue[
        Math.floor(Math.random() * this.foodValue.length)
      ]
      if (this.cognition > this.cognitionMax) this.cognition = this.cognitionMax
    },
    applyDot() {
      if (this.minorDot > 0) this.damage += this.minorDot > 0
      if (this.severeDot > 0)
        this.damage += Math.ceil(Math.random() * 3 + (this.severeDot - 1))
    },
    heal(injuryType) {
      const current = this[injuryType]
      if (current > 0) this[injuryType] = current - 1
    },
  },
  created() {
    this.$store.dispatch('load')
  },
}
</script>

<style lang="stylus" scoped>
@require '../assets/vars.styl'

.spacer-sheet
  flex 0 0 2px
  margin 14px 0
  background-color hsla(0, 0%, 0%, 0.4)

.frame
  width 100px
  height 100px
  background center / contain no-repeat url('https://previews.123rf.com/images/markusgann/markusgann0904/markusgann090400005/4595771-an-illustration-of-a-square-wooden-frame.jpg')
  @media screen and (max-width: wide-tablet-width)
    align-self center
    width 180px
    height 180px
  button
    width 80px
    height 80px
    margin 10px
    border none
    background-color black
    @media screen and (max-width: wide-tablet-width)
      margin 25px
      width 130px
      height 130px
    img
      width 100%
      height 100%
      cursor pointer
      object-fit cover
      object-position center
  button:hover, button:focus
    img
      filter brightness(0.5)
  button:active
    img
      filter brightness(1.5)

.title-row
  justify-content flex-end
  align-items center
  @media screen and (max-width: wide-tablet-width)
    justify-content flex-start
    align-items center
    max-width 100%
    overflow hidden

#char-name
  margin-left 10px
  font-size 2em
  overflow hidden
  @media screen and (max-width: wide-tablet-width)
    margin-top 1ex
    margin-left 0
    width 100%
    font-size 1.7em
  input
    color accent-light
    background-color transparent
    @media screen and (max-width: wide-tablet-width)
      width 100%
      text-align center

#char-title
  margin-left 10px
  padding-bottom 15px
  @media screen and (max-width: wide-tablet-width)
    align-items center
    margin-left 0
    padding-bottom 0
    width 100%
  .title-prefix
    margin-right 0.5ch
    @media screen and (max-width: wide-tablet-width)
      margin-top 0.4ex
  input
    width 40ch
    color accent-light
    background-color transparent
    @media screen and (max-width: wide-tablet-width)
      margin-top 0.4ex
      width 100%
      text-align center
      font-size 1.2em

.trackers
  display grid
  grid-template-columns 1fr 1fr
  grid-gap 5px
  font-size 1.3em
  @media screen and (max-width: wide-tablet-width)
    grid-template-columns 1fr
  > div
    padding 5px
    background-color background-dark
    border-radius 10px
.other-trackers
  display grid
  grid-template-columns 1fr
  grid-auto-rows min-content
  grid-gap 5px
.out-of
  margin-left 1ch

.dmg-grid
  display grid
  grid-template-columns auto auto
  grid-template-rows auto 1px auto 2ex auto
  grid-gap 5px 1ch
.dmg-over-thresh
  grid-column 2
  width 100%
  height 100%
  background-color foreground
.thresh-over-wounds
  grid-column 1 / span 2
  width 100%
  button
    display block
    height 100%
    width 100%
    font-size 0.8em
.rest-label
  padding-right 1ch

.number-entry
  width 2.4ch
  text-align center
  border none
  font-size 1em

#armor-entry
  margin 0 1ch
#meal-type
  flex 1 1 auto
  font-size 0.8em
#eat-button
  flex 0 0 5ch

.injury-add-bttn
  display flex
  flex 0 0 2.5ch
  justify-content center
  align-items center
  text-align center
  font-size 1.5em
  font-weight 700
.injury-list
  display grid
  grid-template-columns 1fr 1fr
  grid-auto-rows min-content
  grid-gap 5px
  @media screen and (max-width: wide-tablet-width)
    grid-template-columns 1fr
.injury-list-entry
  background-color background-dark
  border-radius 5px
  overflow hidden
  button
    padding 0.5ex
    border-top 1px solid button-bg-dark
  @media screen and (max-width: portrait-tablet-width)
    font-size 1.2em
  button + button
    border-left 1px solid button-bg-dark
.injury-label, .injury-type
  padding 4px
.stat-injury-grid
  display grid
  grid-template-columns 3fr 2fr
  padding 0.5ex
  > *:nth-child(1)
    color accent-light

.reference-list
  > h1 + h2
    margin-top .4ex
  > div + .reference-list-section-title
    margin-top 2ex
.reference-list-section-title
  display flex
  flex-direction row
  align-items center
  a
    color unset
  a:hover, a:focus
    color accent-dark
  a::after
    content "❱"
    margin-left 0.5ch
    color accent-link
    font-size 0.8em
  a:hover::after, a:focus::after
    color accent-link-dark
.empty-reference-list
  color foreground-faint
  font-style italic
</style>

<style lang="stylus">
@require '../assets/vars.styl'

.char-attr-grid
  display grid
  grid-template-columns 1fr 1fr
  grid-template-rows 2fr 1fr
  grid-template-areas "input input" "down up"
  @media screen and (max-width: wide-tablet-width)
    grid-template-columns 1fr 1.2fr 1fr
    grid-template-rows 1fr
    grid-template-areas "down input up"
  .number-input-field
    grid-area input
  .number-input-down
    grid-area down
  .number-input-up
    grid-area up

.char-attribute
  max-width 9ch
  background-color field-bg
  border-radius 20px
  font-size 1.2em
  text-align center
  overflow hidden
  @media screen and (max-width: wide-tablet-width)
    max-width unset
    border-radius 25px
    font-size 1.4em
  .attribute-label
    padding .4ex 0 0 0
    @media screen and (max-width: wide-tablet-width)
      padding 1ex 1ch
  .number-input-field
    min-width 2ch
    width 100%
    font-size 1.8em
    order 0
    @media screen and (max-width: wide-tablet-width)
      width 3ch
      font-size 1.4em
  .number-input-bttn
    order 1
    border-radius 0
  @media screen and (max-width: wide-tablet-width)
    .number-input-down
      border-radius 25px 0 0 25px
    .number-input-up
      border-radius 0 25px 25px 0

@media screen and (max-width: wide-tablet-width)
  .char-attribute + .char-attribute
    margin-top 5px

.minor-stat
  input
    width 3ch

.bs-selectbox
  padding 0.6ex 0.5ch 0.6ex 1ch
.bs-option, .bs-option-group
  padding 4px
.food-type-select
  transition border-radius 0.2s
  border-radius 15px 0 0 15px
.food-type-select.open
  border-radius 15px 0 0 0
.food-type-select.open.flipped
  border-radius 0 0 0 15px
.injury-type-select
  width 20ch
  transition border-radius 0.2s
  border-radius 15px 0 0 15px
.injury-type-select.open
  border-radius 15px 0 0 0
.injury-type-select.open.flipped
  border-radius 0 0 0 15px

.reference-list
  .reference-entry-name
    align-self flex-end
  .reference-entry-desc
    margin-top .5ex
</style>

// src/components/CharacterSheet.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte'
  import { onMount, onDestroy } from 'svelte'
  import NumberInput from './NumberInput.svelte'
  import CharacterAttribute from './ChararacterAttribute.svelte'
  import Select from './Select.svelte'
  import InjuryTracker from './InjuryTracker.svelte'
  import ReferenceEntry from './ReferenceEntry.svelte'
  import {
    name,
    title,
    race,
    homeland,
    brawn,
    poise,
    memory,
    wit,
    charisma,
    damage,
    wounds,
    cognition,
    proficiencies,
    mundaneTraits,
    exceptionalTraits,
    minorDot,
    severeDot,
    slowed,
    immobile,
    weakened,
    drained,
    staggered,
    unstable,
    confused,
    amnesia,
    distracted,
    dazed,
    activeCharacter,
  } from '../character-store'
import ChararacterAttribute from './ChararacterAttribute.svelte'

  const dispatch = createEventDispatcher()
  const raceOptions = [
    { name: 'Human' },
    { name: 'Wyrm' },
    { name: 'Wandering Spirit' },
    { name: 'Stone Dweller' },
    { name: 'Bofo' },
    { name: 'Carapact' },
  ]
  const foodTypes = [
    {
      name: 'Questionable',
      value: [-4, 1],
    },
    {
      name: 'Snack',
      value: [2],
    },
    {
      name: 'Decent Meal',
      value: [4],
    },
    {
      name: 'Good Meal',
      value: [8],
    },
    {
      name: 'Hearty Meal',
      value: [12],
    },
  ]
  const injuryTypes = [
    {
      name: '',
      value: '',
    },
    {
      name: 'Minor',
      children: [
        {
          name: 'Minor DoT',
          value: 'minorDot',
        },
        {
          name: 'Slowed',
          value: 'slowed',
        },
        {
          name: 'Weakened',
          value: 'weakened',
        },
        {
          name: 'Staggered',
          value: 'staggered',
        },
        {
          name: 'Confused',
          value: 'confused',
        },
        {
          name: 'Distracted',
          value: 'distracted',
        },
      ],
    },
    {
      name: 'Severe',
      children: [
        {
          name: 'Severe DoT',
          value: 'severeDot',
        },
        {
          name: 'Immobile',
          value: 'immobile',
        },
        {
          name: 'Drained',
          value: 'drained',
        },
        {
          name: 'Unstable',
          value: 'unstable',
        },
        {
          name: 'Amnesia',
          value: 'Amnesia',
        },
        {
          name: 'Dazed',
          value: 'dazed',
        },
      ],
    },
  ]

  let unsubscribe
  let selectedFoodType: Array<number> = [2]
  let selectedInjuryType: string = ''
  let currentInjury: number = 0

  $: threshold = 4 + (2 * $brawn) + $poise
  $: dead = $wounds >= threshold
  $: cognitionMax = $wit > -1 ? 8 + $wit * 8 : 8 / Math.pow(2, Math.abs($wit))
  $: totalDot = ($minorDot > 0 ? `${$minorDot}` : '') + ($minorDot > 0 && $severeDot > 0 ? ' + ' : '') + ($severeDot > 0 ? `${$severeDot}d4` : '')
  $: totalSlow = $immobile > 0 ? 'Speed 0' : `Speed -${$slowed}`
  $: totalWeaken = $drained > 0 ? 'Brawn -2' : `Brawn -${$weakened}`
  $: totalStagger = $unstable > 0 ? 'Poise -2' : `Poise -${$staggered}`
  $: totalConfusion = $amnesia > 0 ? 'Memory -2' : `Memory -${$confused}`
  $: totalDistraction = $dazed > 0 ? 'Wit -2' : `Wit -${$distracted}`

  function loadLastCharacter() {
    const serialCharacter = localStorage.getItem('activeCharacter')
    if (serialCharacter) {
      const lastCharacter = JSON.parse(serialCharacter)
      $name = lastCharacter.name
      $title = lastCharacter.title
      $race = lastCharacter.race
      $homeland = lastCharacter.homeland
      $brawn = lastCharacter.brawn
      $poise = lastCharacter.poise
      $memory = lastCharacter.memory
      $wit = lastCharacter.wit
      $charisma = lastCharacter.charisma
      $damage = lastCharacter.damage
      $wounds = lastCharacter.wounds
      $cognition = lastCharacter.cognition
      $proficiencies = lastCharacter.proficiencies
      $mundaneTraits = lastCharacter.mundaneTraits
      $exceptionalTraits = lastCharacter.exceptionalTraits
      $minorDot = lastCharacter.injuries.minorDot
      $severeDot = lastCharacter.injuries.severeDot
      $slowed = lastCharacter.injuries.slowed
      $immobile = lastCharacter.injuries.immobile
      $weakened = lastCharacter.injuries.weakened
      $drained = lastCharacter.injuries.drained
      $staggered = lastCharacter.injuries.staggered
      $unstable = lastCharacter.injuries.unstable
      $confused = lastCharacter.injuries.confused
      $amnesia = lastCharacter.injuries.amnesia
      $distracted = lastCharacter.injuries.distracted
      $dazed = lastCharacter.injuries.dazed
    }
  }
  function saveActiveCharacter(character: any) {
    localStorage.setItem('activeCharacter', JSON.stringify(character))
  }
  function resolveDamage() {
    if ($damage < threshold) return
    const newWounds = Math.floor($damage / threshold)
    if (newWounds > 2) $wounds = threshold
    else $wounds += newWounds
    $damage = $wounds
  }
  function revive() {
    $wounds = Math.max(0, threshold - 1)
    $damage = $wounds
  }
  function sleep(amount: number) {
    $cognition = Math.min(
      $cognition + Math.ceil(amount * cognitionMax),
      cognitionMax,
    )
  }
  function eat() {
    const selectedValue = Math.floor(Math.random() * selectedFoodType.length)
    $cognition += selectedFoodType[selectedValue]
    if ($cognition > cognitionMax) $cognition = cognitionMax
  }
  function applyDot() {
    $damage += $minorDot
    if ($severeDot > 0)
      $damage += Math.ceil(Math.random() * 3 + ($severeDot - 1))
  }
  function close() {
    dispatch('close')
  }
  function removeFromList(values: Array<any>, index: number, count: number = 1) {
    values.splice(index, count)
    return values
  }
  function addInjury() {
    switch (selectedInjuryType) {
      case 'minorDot': $minorDot++; break;
      case 'severeDot': $severeDot++; break;
      case 'slowed': $slowed++; break;
      case 'immobile': $immobile++; break;
      case 'weakened': $weakened++; break;
      case 'drained': $drained++; break;
      case 'staggered': $staggered++; break;
      case 'unstable': $unstable++; break;
      case 'confused': $confused++; break;
      case 'amnesia': $amnesia++; break;
      case 'distracted': $distracted++; break;
      case 'dazed': $dazed++; break;
    }
    selectedInjuryType = ''
    currentInjury = 0
  }

  onMount(() => {
    loadLastCharacter()
    unsubscribe = activeCharacter.subscribe(saveActiveCharacter)
  })
  onDestroy(() => {if (unsubscribe) unsubscribe()})
</script>

<style lang="stylus">
  @require '../assets/vars.styl'

  .char-sheet
    .section-divider
      width 100%
      height 1px
      margin 15px 0
      background-color accent-pri
    .section-header
      font-size 1.6em
      font-weight bold
      a
        color inherit
      a:hover, a:focus
        color accent-dark
      a::after
        content "❱"
        margin-left 0.5ch
        color accent-link
        font-size 0.8em
      a:hover::after, a:focus::after
        color accent-link-dark
  .char-portrait-change
    display flex
    flex 0 0 auto
    justify-content center
    align-items center
    width 175px
    height 175px
    margin-bottom 15px
  .char-portrait-img
    width 150px
    height 150px
  .char-id
    display flex
    flex-direction column
    align-items center
    font-size 1.2em
  .char-id-entry
    width 100%
    > * + *
      margin-top 5px
  .char-id-name-input
    font-size 1.4em
    width 100%
    padding 5px 10px
    color accent-light
    border-radius 10px
    overflow hidden
  .char-id-title
    display flex
    flex-direction row
    align-items center
    width 100%
    padding-left 10px
  .char-id-title-input
    flex 1 1 100%
    margin-left 0.5ch
    padding 5px 0.5ch
    color accent-light
    border-radius 10px
    overflow hidden
  .char-id-race
    display flex
    flex-direction row
    align-items center
    width 100%
    padding-left 10px
  .char-id-homeland
    display flex
    flex-direction row
    align-items center
    width 100%
    padding-left 10px
  .char-id-homeland-input
    flex 1 1 100%
    padding 5px 0.5ch
    margin-left 0.5ch
    color accent-light
    border-radius 10px
    overflow hidden
  .char-trackers
    display grid
    grid-template-columns auto
    grid-gap 5px
    > div
      padding 10px
      background-color background-sub
      border-radius 15px
  .char-dmg-grid
    display grid
    grid-template-columns 1fr min-content
    grid-template-rows auto 1px auto auto auto
    grid-gap 5px
  .char-other-stats
    display grid
    grid-template-columns auto
    grid-auto-rows min-content
    grid-gap 10px
    background-color background-sub
    border-radius 15px
  .char-other-trackers
    display grid
    grid-template-columns auto
    grid-auto-rows min-content
    grid-gap 10px
  .char-dmg-grid-left
    grid-column 1
  .char-dmg-grid-right
    grid-column 2
  .char-dmg-grid-span
    grid-column 1 / span 2
  .char-dmg-divider
    background-color foreground
  .char-injury-trackers
    display grid
    grid-template-columns 1fr
    grid-gap 15px
    margin-top 15px
  .char-empty-ref-list
    font-size 0.8em
    color foreground-faint
  @media screen and (min-width: partial-width)
    .char-id
      flex-direction row
    .char-portrait-change
      margin-bottom 0
      margin-right 15px
    .char-trackers
      grid-template-columns 1fr 1fr
    .char-injury-trackers
      grid-template-columns 1fr 1fr

  :global
    .char-sheet
      .basic-input
        padding 0.3em 1.25ch
      .select-input
        border-radius 15px
      .select-input.right
        border-radius 0 15px 15px 0
      .select-input.left
        border-radius 15px 0 0 15px
      .select-label
        padding 5px 10px
      .char-attrs
        font-size 1.2em
      .char-attr
        display flex
        flex-direction row
        justify-content space-between
        background-color background-sub
        border-radius 15px
        overflow hidden
        & + .char-attr
          margin-top 10px
        .number-input-field
          width 3ch
      .char-attr-label
        padding 5px 1ch
      .ref-entry-header
        display flex
        flex-direction row
        justify-content space-between
        align-items flex-end
        margin-top 15px
        a
          color inherit
        a:hover, a:focus
          color accent-dark
        a::after
          content "❱"
          margin-left 0.5ch
          color accent-link
          font-size 0.8em
        a:hover::after, a:focus::after
          color accent-link-dark
        .two-stage-bttn
          padding 0.25em 1ch
          font-size 0.9em
          border-radius 15px
        .two-stage-bttn.confirm
          border-radius 15px 0 0 15px
        .two-stage-bttn.abort
          border-radius 0 15px 15px 0
      .ref-entry-name
        font-size 1.25em
        color foreground-minor
      .injury-tracker
        height min-content
      .injury-action-bttn
        border 1px solid accent-dark
      .injury-type
        color accent-light
    .char-id-race
      .select-input
        flex 1 0 20ch
        margin-left 0.5ch
    .char-trackers
      .number-input-field
        width 3ch
    .char-injury-type-select
      width 14ch

    @media screen and (min-width: partial-width)
      .char-sheet
        .char-attrs
          flex-direction row
          justify-content space-between
        .char-attr
          flex 0 0 110px
          flex-direction column
          text-align center
          & + .char-attr
            margin-top 0
          .number-input
            display grid
            grid-template-columns 1fr 1fr
            grid-template-rows 2.5em 1.2em
          .number-input-field
            grid-column 1 / span 2
            grid-row 1
            width 100%
            font-size 2em
            background-color transparent
          .number-input-button
            grid-row 2
          .number-input-button.decrement
            border-radius 0
          .number-input-button.increment
            border-radius 0
        .char-attr-label
          font-size 1em
          padding-bottom 0

</style>

<div class="char-sheet">
  <div class="char-sheet-section char-id">
    <button class="char-portrait-change">
      <img class="char-portrait-img" src="#" alt="">
    </button>
    <div class="col char-id-entry">
      <input class="char-id-name-input" 
            type=text bind:value={$name}
            placeholder="Character Name" />
      <div class="char-id-title">
        <div>the</div>
        <input class="char-id-title-input"
              type=text bind:value={$title}
              placeholder="Character Title" />
      </div>
      <div class="char-id-race">
        <div>a</div>
        <Select options={raceOptions} initial={$race} on:select={event => $race = event.detail.value} />
      </div>
      <div class="char-id-homeland">
        <div>from</div>
        <input type=text class="char-id-homeland-input" placeholder="Homeland" bind:value={$homeland} />
      </div>
    </div>
  </div>
  <div class="section-divider" />
  <div class="char-sheet-section char-attrs col">
    <ChararacterAttribute bind:value={$brawn}>Brawn</ChararacterAttribute>
    <ChararacterAttribute bind:value={$poise}>Poise</ChararacterAttribute>
    <ChararacterAttribute bind:value={$memory}>Memory</ChararacterAttribute>
    <ChararacterAttribute bind:value={$wit}>Wit</ChararacterAttribute>
    <ChararacterAttribute bind:value={$charisma}>Charisma</ChararacterAttribute>
  </div>
  <div class="section-divider" />
  <div class="char-sheet-section char-trackers">
  {#if dead}
    <div class="char-death-panel">
      <div>{$name} is Dead</div>
      <button class="basic-input" on:click={revive}>Revive</button>
    </div>
  {:else}
    <div class="char-dmg-grid">
      <div class="char-dmg-grid-left">Damage</div>
      <div class="char-dmg-grid-right row m-center">
        <NumberInput bind:value={$damage} min={0} />
      </div>
      <div class="char-dmg-grid-right char-dmg-divider" />
      <div class="char-dmg-grid-left">Threshold</div>
      <div class="char-dmg-grid-right row m-center">{threshold}</div>
      <button class="basic-input char-dmg-grid-span" on:click={resolveDamage}>Resolve</button>
      <div class="char-dmg-grid-left">Wounds</div>
      <div class="char-dmg-grid-right row m-center">{$wounds}</div>
    </div>
    <div class="char-other-stats">
      <div class="row m-spaced c-center">
        <div>Armor</div>
        <NumberInput min={0} max={100} setonly />
      </div>
      <div class="row m-spaced c-center">
        <div>Speed</div>
        <NumberInput min={0} max={100} setonly />
      </div>
    </div>
    <div class="char-other-trackers">
      <div class="row m-spaced c-center">
        <div>Cognition</div>
        <div class="row c-center">
          <NumberInput bind:value={$cognition} min={0} max={cognitionMax} />
          <div class="txt-suffix">of {cognitionMax}</div>
        </div>
      </div>
      <div class="row">
        <button class="basic-input left grow" on:click={() => sleep(0.5)}>Nap</button>
        <button class="basic-input right grow" on:click={() => sleep(1)}>Sleep</button>
      </div>
      <div class="row">
        <Select _class="left grow"
                on:select={event => selectedFoodType = event.detail.value}
                options={foodTypes}
                initial={1} />
        <button class="basic-input right fw-short" on:click={eat}>Eat</button>
      </div>
    </div>
  {/if}
  </div>
  <div class="section-divider" />
  <div class="char-sheet-section char-injuries">
    <div class="section-header">Injuries</div>
    <div class="row m-spaced c-center">
      <div class="row">Add Injury</div>
      <div class="row">
        <Select _class="left char-injury-type-select"
                on:select={event => selectedInjuryType = event.detail.value}
                options={injuryTypes}
                bind:current={currentInjury} />
        <button class="basic-input right"
                on:click={addInjury}
                disabled={selectedInjuryType === ''}>
          +
        </button>
      </div>
    </div>
    <div class="char-injury-trackers">
      <InjuryTracker bind:minor={$minorDot}
                     bind:severe={$severeDot}
                     effect={totalDot}
                     actions={[{name: 'Apply', handler: applyDot}]}>
        Damage Over Time
      </InjuryTracker>
      <InjuryTracker bind:minor={$slowed}
                     bind:severe={$immobile}
                     effect={totalSlow}>
        Slowed
      </InjuryTracker>
      <InjuryTracker bind:minor={$weakened}
                     bind:severe={$drained}
                     effect={totalWeaken}>
        Weakened
      </InjuryTracker>
      <InjuryTracker bind:minor={$staggered}
                     bind:severe={$unstable}
                     effect={totalStagger}>
        Staggered
      </InjuryTracker>
      <InjuryTracker bind:minor={$confused}
                     bind:severe={$amnesia}
                     effect={totalConfusion}>
        Confused
      </InjuryTracker>
      <InjuryTracker bind:minor={$distracted}
                     bind:severe={$dazed}
                     effect={totalDistraction}>
        Distracted
      </InjuryTracker>
    </div>
  </div>
  <div class="section-divider" />
  <div class="char-sheet-section char-ref-list char-proficiencies col">
    <div class="section-header">
      <a href="/characters/proficiencies" on:click={close}>Proficiencies</a>
    </div>
  {#if $proficiencies.length > 0}
  {#each $proficiencies as proficiency, i (proficiency)}
    <ReferenceEntry target={proficiency}
                    on:follow={close}
                    on:remove={() => $proficiencies = removeFromList($proficiencies, i)}
                    baseRulesUrl="/characters/proficiencies"
                    baseRefUrl="/ref/proficiencies" />
  {/each}
  {:else}
    <div class="char-empty-ref-list">Your character has no proficiencies yet...</div>
  {/if}
  </div>
  <div class="section-divider" />
  <div class="char-sheet-section char-ref-list char-traits col">
    <div class="section-header">
      <a href="/characters/traits/mundane" on:click={close}>Mundane Traits</a>
    </div>
  {#if $mundaneTraits.length > 0}
  {#each $mundaneTraits as trait, i (trait)}
    <ReferenceEntry target={trait}
                    on:follow={close}
                    on:remove={() => $mundaneTraits = removeFromList($mundaneTraits, i)}
                    baseRulesUrl="/characters/traits/mundane"
                    baseRefUrl="/ref/traits/mundane" />
  {/each}
  {:else}
    <div class="char-empty-ref-list">Your character has no mundane traits yet...</div>
  {/if}
  </div>
  <div class="char-sheet-section char-ref-list char-traits col">
    <div class="section-divider" />
    <div class="section-header">
      <a href="/characters/traits/exceptional" on:click={close}>Exceptional Traits</a>
    </div>
  {#if $exceptionalTraits.length > 0}
  {#each $exceptionalTraits as trait, i (trait)}
    <ReferenceEntry target={trait}
                    on:follow={close}
                    on:remove={() => $exceptionalTraits = removeFromList($exceptionalTraits, i)}
                    baseRulesUrl="/characters/traits/exceptional"
                    baseRefUrl="/ref/traits/exceptional" />
  {/each}
  {:else}
    <div class="char-empty-ref-list">Your character has no exceptional traits yet...</div>
  {/if}
  </div>
</div>
