// src/components/NavTree.svelte
<script lang="ts">
import { onMount } from 'svelte'

class NavTreeRoute {
  name: string
  path: string
  children?: Array<NavTreeRoute>
  open?: boolean
}
class TieredStyle {
  style: string
  scalar: string
  flat?: string
  constructor(style: string, scalar: string, flat?: string) {
    this.style = style
    this.scalar = scalar
    this.flat = flat
  }
  atDepth(depth: number) {
    return (
      `calc(${depth} * ${this.scalar}` +
      (this.flat ? ` + ${this.flat}` : '') +
      ')'
    )
  }
  apply(element: HTMLElement, depth: number) {
    element.style.setProperty(this.style, this.atDepth(depth))
  }
}

export let routes: Array<NavTreeRoute>
export let activePath: string = ''
export let basePath: string = ''
export let depth: number = 0
export let arrowContent: string = '❯'
export let tieredStyles: Array<TieredStyle> = [
  new TieredStyle('padding-left', '1.2em', '1.5em'),
]

for (let route of routes)
  if (route.children) route.open = checkActive(activePath, route.path)

let labels: Array<HTMLElement> = []

onMount(() => {
  for (let label of labels)
    for (let tieredStyle of tieredStyles) tieredStyle.apply(label, depth)
})

function checkActive(activePath: string, targetPath: string): boolean {
  return activePath.startsWith(targetPath)
}
</script>

<div class="nav-tree">
  {#each routes as route, i (route.name)}
    <div
      class="nav-tree-label nav-tree-label-{depth}"
      class:active="{checkActive(activePath, basePath + route.path)}"
      class:exactActive="{activePath === basePath + route.path}"
      bind:this="{labels[i]}"
    >
      {#if route.children}
        <div
          class="nav-tree-arrow"
          class:open="{route.open}"
          on:click="{() => (route.open = !route.open)}"
        >
          {@html arrowContent}
        </div>
      {/if}
      <a
        href="{basePath + route.path}"
        class="nav-tree-label-text"
        on:keyup|stopPropagation="{e => {
          if (!e.isComposing && e.key === ' ') route.open = !route.open
        }}"
      >
        {route.name}
      </a>
    </div>
    {#if route.children && route.open}
      <svelte:self
        routes="{route.children}"
        activePath="{activePath}"
        basePath="{basePath + (route.path ? route.path : '')}"
        depth="{depth + 1}"
        arrowContent="{arrowContent}"
        class="nav-tree-children"
      />
    {/if}
  {/each}
</div>

<style lang="stylus">
  arrow-width = 1.2em
  .nav-tree
    display flex
    flex-direction column
    position relative
  .nav-tree-label
    display flex
    flex-direction row
    align-items center
  .nav-tree-label.active
    background-color hsla(0, 0, 100%, 0.05)
  .nav-tree-label.exactActive
    background-color hsla(0, 0, 100%, 0.14)
  .nav-tree-arrow
    display flex
    justify-content center
    align-items center
    position absolute
    margin-left -(arrow-width)
    width arrow-width
    height arrow-width
    user-select none
    transition transform 0.2s
    transform rotate(0turn)
  .nav-tree-label-text
    flex 1 1 100%
    display flex
    flex-direction row
    height 100%
    color inherit
  .nav-tree-arrow.open
    transform rotate(0.25turn)
</style>

// src/components/NavTree.vue
<template>
  <div>
    <div
      v-for="route of routes"
      :key="route.name"
      :class="['nav-tree-node', { open: isOpen }]"
    >
      <router-link
        :to="basePath + route.path"
        v-slot="{ href, isActive, isExactActive }"
      >
        <div
          :class="[
            'nav-tree-label',
            { active: isActive },
            { exact: isExactActive },
          ]"
          ref="labels"
        >
          <div
            v-if="route.children !== undefined"
            v-html="arrow"
            :class="['nav-tree-arrow']"
            ref="arrows"
          />
          <g-link
            v-if="route.path !== undefined"
            :to="href"
            :class="['nav-tree-link']"
            >{{ route.name }}</g-link
          >
          <div v-else>{{ route.name }}</div>
        </div>
      </router-link>
      <nav-tree
        v-if="route.children !== undefined"
        :routes="route.children"
        :class="['nav-tree-child']"
        :basePath="route.path !== undefined ? basePath + route.path : basePath"
        :depth="depth + 1"
        :open="false"
        ref="children"
      />
    </div>
  </div>
</template>

<script>
export default {
  name: 'nav-tree',
  props: {
    routes: {
      type: Array,
      default: [],
    },
    basePath: {
      type: String,
      default: '',
    },
    depth: {
      type: Number,
      default: 0,
    },
    open: {
      type: Boolean,
      default: true,
    },
    arrow: {
      type: String,
      default: '❯',
    },
    tieredStyles: {
      type: Array,
      default: function() {
        return [
          {
            style: 'padding-left',
            scalar: '20px',
            flat: '1.2em',
          },
        ]
      },
    },
  },
  data: function() {
    return {
      isOpen: false,
    }
  },
  methods: {
    calcTieredStyles(tieredStyles) {
      for (var label of this.$refs.labels) {
        for (var tieredStyle of tieredStyles) {
          const calc =
            tieredStyle.flat !== undefined
              ? `calc(${this.depth} * ${tieredStyle.scalar} + ${
                  tieredStyle.flat
                })`
              : `calc(${this.depth} * ${tieredStyle.scalar})`
          label.style.setProperty(tieredStyle.style, calc)
        }
      }
    },
  },
  mounted() {
    this.isOpen = this.open
    this.calcTieredStyles(this.tieredStyles)
    const arrows = this.$refs.arrows
    if (arrows === undefined) return
    for (var i = 0; i < arrows.length; i++) {
      const arrow = this.$refs.arrows[i]
      const text = arrow.nextSibling
      const child = this.$refs.children[i]
      arrow.onclick = () => {
        child.isOpen = !child.isOpen
        arrow.classList.toggle('open')
      }
      text.onclick = () => {
        child.isOpen = true
        arrow.classList.add('open')
      }
    }
  },
}
</script>

<style lang="stylus">
.nav-tree-node
  display none
  flex-direction column
.nav-tree-node.open
  display flex
.nav-tree-label
  display flex
  flex-direction row
  align-items center
.nav-tree-label.active
  background-color hsla(0, 0, 100%, 0.05)
.nav-tree-label.active.exact
  background-color hsla(0, 0, 100%, 0.2)
.nav-tree-arrow
  transition transform 0.2s
  display flex
  justify-content center
  align-items center
  margin-left -1em
  width 1em
  height 1em
  cursor pointer
  user-select none
  transform rotate(0turn)
.nav-tree-arrow.open
  transform rotate(0.25turn)
.nav-tree-link
  color inherit
</style>
