// src/components/RefAdder.vue
<template>
  <button class="adder" @click="click">+</button>
</template>

<script>
export default {
  props: {
    target: {
      type: String,
      default: '',
    },
    mutation: {
      type: String,
      default: '',
    },
  },
  methods: {
    click: function() {
      this.$store.commit(this.mutation, this.target)
      this.$store.dispatch('save')
    },
  },
}
</script>

<style lang="stylus" scoped>
.adder
  display flex
  justify-content center
  align-items center
  width 1em
  height 1em
  margin-left 1ch
  border-radius 9999px
  overflow hidden
</style>

// src/components/RefAdder.svelte
<script lang="ts">
  import { proficiencies, mundaneTraits, exceptionalTraits } from '../character-store'

  export let type: string
  export let target: string

  function add() {
    switch (type) {
      case 'proficiency':
        if ($proficiencies.includes(target)) return
        $proficiencies = [...$proficiencies, target]
        return
      case 'mundaneTrait':
        if ($mundaneTraits.includes(target)) return
        $mundaneTraits = [...$mundaneTraits, target]
        return
      case 'exceptionalTrait':
        if ($exceptionalTraits.includes(target)) return
        $exceptionalTraits = [...$exceptionalTraits, target]
        return
    }
  }
</script>

<style lang="stylus">
  .ref-adder
    display flex
    justify-content center
    align-items center
    width 1.1em
    height 1.1em
    margin-left 1ch
    border-radius 9999px
    text-align center
</style>

<button class="ref-adder" on:click={add}>+</button>
