// src/components/TwoStageButton.vue
<template>
  <div>
    <button
      :class="['two-stage-bttn two-stage-prime', { hidden: primed }]"
      @click="primed = true"
    >
      <slot />
    </button>
    <button
      :class="['two-stage-bttn two-stage-abort', { hidden: !primed }]"
      @click="primed = false"
    >
      {{ abortText }}
    </button>
    <button
      :class="['two-stage-bttn two-stage-confirm', { hidden: !primed }]"
      @click="confirm"
    >
      {{ confirmText }}
    </button>
  </div>
</template>

<script>
export default {
  props: {
    abortText: {
      type: String,
      default: 'X',
    },
    confirmText: {
      type: String,
      default: '✓',
    },
  },
  data() {
    return {
      primed: false,
    }
  },
  methods: {
    confirm() {
      this.$emit('click')
    },
  },
}
</script>

<style lang="stylus" scoped>
div
  display flex
  flex-direction row
.hidden
  display none
</style>

// src/components/TwoStageButton.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte'

  const dispatch = createEventDispatcher()

  export let confirmText: string = 'Yes'
  export let abortText: string = 'No'
  export let _class: string = ''

  let primed = false
  
</script>

<style lang="stylus">
  .two-stage-bttn-container
    display flex
    flex-direction row
  .two-stage-bttn
    display block
  .two-stage-bttn.hidden
    display none
</style>

<div class={'two-stage-bttn-container ' + _class}>
  <button class="two-stage-bttn two-stage-prime"
          class:hidden={primed}
          on:click={() => primed = true}>
    <slot />
  </button>
  <button class="two-stage-bttn confirm"
          class:hidden={!primed}
          on:click={() => { dispatch('click'); primed = false; }}>
    {confirmText}
  </button>
  <button class="two-stage-bttn abort"
          class:hidden={!primed}
          on:click={() => primed = false}>
    {abortText}
  </button>
</div>
